### ISSUE TITLE
Python pre-commit hook config is not updated with this

### ISSUE THREAD

**Issue by onnimonni** [swappiehq/github-actions#11]
For example `.pre-commit-config.yaml` the file contains a step like this:
```yaml
repos:
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3.10
```

And we should update the language_version part to the same as in asdf is using
